### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by guykogus** [stormpath/stormpath-sdk-swift#26]

**Comment by edjiang** [comment]
Hey Guy! Thanks for opening up this issue. I have some feature enhancements planned in the next 1-2 months, and I was planning on migrating to Swift 3 after implementing those features. There might also still be a few changes to the language before Swift 3 goes live, so I'd like to delay if possible. 

When are you planning on migrating your code to Swift 3? If you're looking at sooner than later, I can consider moving Swift 3 earlier on my timeline, so you can use Stormpath with your codebase. 

(Just as a FYI, you won't be able to deploy to the App Store in Swift 3 until Xcode 8 comes out of beta. So if you're planning on building an iOS app in Swift 3 right now, I'd suggest you stay on Swift 2 for the foreseeable future. )

**Comment by guykogus** [comment]
Hey there. We're far from ready to deploy our app, I just wanted to get the idea out there to migrate to swift 3. When you're ready to move on and you need any help, please let me know.

**Comment by edjiang** [comment]
Awesome, thanks! Please give me a heads up when you're planning on moving to Swift 3, so I can help support your team in its migration =]

**Comment by guykogus** [comment]
I ran the convert job in Xcode 8 (beta 3) and it went pretty smoothly. The only breaking change I can find is that it changes all the enum values to camelCase. Want me to create a pull request from my fork?

**Comment by edjiang** [comment]
Yep! The new enum convention will take some getting used to. Thanks, that'd be awesome!

**Comment by edjiang** [comment]
See https://github.com/stormpath/stormpath-sdk-ios/tree/swift3
