### ISSUE TITLE
Social Login

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-sdk-swift#3]
- [x] Facebook
- [x] Google
- [ ] Github
- [ ] LinkedIn

**Comment by edjiang** [comment]
I did some testing today and yesterday on the social SDKs to get a better idea of how they work and what we'd need to do to support them.

Currently, we're still waiting on the `express-stormpath` API to support a social login flow, but it should be completed soon. When that happens, we'll be able to pass a social provider token to the endpoint, and retrieve and access & refresh token from Stormpath.

Here's my thoughts on integrating with them: 

Facebook and Google's SDKs are relatively well-designed and I would not hesitate to suggest asking our users to integrate their SDKs. As time goes on, we could probably do more with them.

LinkedIn's SDK is a bit more clunky and I'd be hesitant to ask users to do this. GitHub doesn't support mobile very well so we'd have to implement the OAuth flow ourselves. I would elect to wait a bit for these two integrations as we figure out a more general way to support social providers.

**Comment by edjiang** [comment]
Yeah, in addition the LinkedIn SDK for mobile doesn't give you an access token that's usable on the server, but only on the mobile SDK. We would need to go through the normal OAuth flow to get an auth code (and then pass it to the server to get an access token).

**Comment by edjiang** [comment]
Facebook and Google added in d16eeeb. GitHub / LinkedIn will be added in the future once there's more backend improvements.
