### ISSUE TITLE
access token not persisted to keychain when using iOS simulator

### ISSUE THREAD

**Issue by BrandonNott** [stormpath/stormpath-sdk-swift#32]
Using Xcode 8.1 and iOS Simulator - iOS 10.1 w/ Swift 3:

The access token and refresh token are not persisted to the keychain when running the app in the simulator.  

I have not encountered this issue running the app on an actual device.

This bug also affects the example project at https://github.com/stormpath/stormpath-ios-example

**Comment by BrandonNott** [comment]
This appears to be an apple bug related to http://stackoverflow.com/questions/38456471/secitemadd-always-returns-error-34018-in-xcode-8-in-ios-10-simulator

A temporary workaround is to run on the iOS 9.X simulator instead which works fine for me.

**Comment by edjiang** [comment]
Yep! It's been really annoying the past few months, but it should be fixed in Xcode 8.2 =] Let me know if you have any other questions; I'll leave this issue open in case others are having the same issue.

**Comment by edjiang** [comment]
Update: Xcode 8.2 is now out of beta, so hopefully people will upgrade soon and stop experiencing this problem =]
