### ISSUE TITLE
CustomData Access

### ISSUE THREAD

**Issue by ghost** [stormpath/stormpath-sdk-swift#36]
I need the data from CustomData on my user data, but when i try
to catch the values from the **account**  object i got an console error :

`**customData	String?	nil	none**
`

I check my portal and the info is there, but i can't access on Swift 3 always show string nil.

How can i access to my custom data? 

Regards.

**Comment by edjiang** [comment]
Hey Ulises,

With the Client API, you must explicitly enable access to customData from the frontend, in case you're using it to store user-sensitive data.

You can access this setting from the Stormpath Admin Console, and going to your application > Policies > Client API > `/me`, and enabling access to customData. 

Hope this helps!

![screen shot 2017-01-17 at 2 22 09 pm](https://cloud.githubusercontent.com/assets/918770/22042520/695804f0-dcc0-11e6-957b-02e4d31e36d9.png)
